env:
  browser: true
  node: true
  es2021: true
parser: 
  "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: 
  no-console: 0
